- name: Clone .vim
  git:
    repo: "git@github.com:elyezer/.vim.git"
    dest: "~/.vim"
    key_file: "~/.ssh/id_rsa"

- name: Create a directory if it does not exist
  file:
    path: "~/.config/nvim"
    state: directory
    mode: "0755"

- name: Create a directory if it does not exist
  file:
    src: "~/.vim/vimrc"
    dest: "~/.config/nvim/init.vim"
    state: link
    mode: "0644"
