---
- name: Import RPM Fusion RPM GPG keys
  rpm_key:
    state: present
    key: "{{ item }}"
  loop:
    - https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
    - https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020

- name: Add RPM Fusion repos
  dnf:
    state: present
    name:
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm

- name: Upgrade all packages
  dnf:
    name: "*"
    state: latest

- name: Install DNF packages
  dnf:
    name:
      - fira-code-fonts
      - fzf
      - git
      - gnome-tweaks
      - kitty
      - neovim
      - npm
      - pipx
      - python3-neovim
      - ripgrep
      - tmux
      - util-linux-user  # provides chsh
      - zsh
